receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
otlphttp:
  endpoint: "{DATA_UPLOAD_ENDPOINT}/20200101/opentelemetry/private"
  headers:
    Authorization: "dataKey {DATA_KEY}"
otlphttp/metrics:
  endpoint: "{DATA_UPLOAD_ENDPOINT}/20200101/opentelemetry"
  headers:
    Authorization: "dataKey {DATA_KEY}"
service:
pipelines:
  traces:
    receivers: [otlp]
    exporters: [otlphttp]
  metrics:
    receivers: [otlp]
    exporters: [otlphttp/metrics]